### ISSUE TITLE
Coverity scan results from vhostmd 1.1

### ISSUE THREAD

**Issue by rwmjones** [vhostmd/vhostmd#6]
Thought you'd be interested in Coverity scan results against vhostmd 1.1.  I have not gone through these yet so there will be a mix of real problems, false positives and perhaps things which have already been fixed.

I'm unable to attach it because github breaks, so linked here:
http://oirase.annexia.org/tmp/vhostmd-scan-results.txt

**Comment by jfehlig** [comment]
Thanks for the report. I doubt any have been fixed since 1.1, but do hope to have time soon to review the results in more detail.

**Comment by jfehlig** [comment]
I've posted a patch series to the virt-tools-list that address most of the coverity complaints

https://www.redhat.com/archives/virt-tools-list/2020-January/msg00039.html

Also available in my branch here https://github.com/jfehlig/vhostmd/tree/coverity-fixes

**Comment by jfehlig** [comment]
The patches were merged long ago but the issue never closed. Doing so now...
