### ISSUE TITLE
vhostmd.xml requires libvirt to be installed

### ISSUE THREAD

**Issue by rwmjones** [vhostmd/vhostmd#7]
vhostmd.xml requires libvirt to be installed, simply to print the "virtualization vendor":

https://github.com/vhostmd/vhostmd/blob/99995e4ba138f43b277620bd43a096c72f354548/vhostmd.xml#L54-L57

We think this is a pretty heavyweight requirement because libvirt is a metapackage which pulls in a lot of stuff that might not be needed on a minimalistic hypervisor.  The same information is available in any RPM, eg:
```
$ rpm -q --qf '%{VENDOR}\n' -qf /etc/os-release 
Fedora Project
```

However making that change would break `VirtualizationProductInfo` which seems to print the libvirt version:

https://github.com/vhostmd/vhostmd/blob/99995e4ba138f43b277620bd43a096c72f354548/vhostmd.xml#L61-L65

It seems pretty odd that this prints either the version of Xen or the version of libvirt - the two are not analogous.  Therefore we think what you'd really want to know here is the version of KVM, but that is really the host kernel version.  So for this I'd change it to:

```uname -r```

@jfehlig - what do you think about these sorts of changes?

**Comment by rwmjones** [comment]
Downstream discussion: https://bugzilla.redhat.com/show_bug.cgi?id=1897130

**Comment by jfehlig** [comment]
> We think this is a pretty heavyweight requirement because libvirt is a metapackage which pulls in a lot of stuff that might not be needed on a minimalistic hypervisor. The same information is available in any RPM, eg:
> 
> ```
> $ rpm -q --qf '%{VENDOR}\n' -qf /etc/os-release 
> Fedora Project
> ```

libvirt has been a metapackage in SUSE for ages now, and like the RedHat one pulls in everything. I agree it is super heavyweight and /etc/os-release is a good candidate for determining vendor. IIRC, openSUSE Factory is/was moving towards /usr/etc for distribution provided configuration files and /etc for local admin config. Is Fedora doing something similar? Even so I doubt /etc/os-release would be moved to /usr/etc/os-release since I think that would break a *lot* of stuff.

> It seems pretty odd that this prints either the version of Xen or the version of libvirt - the two are not analogous. Therefore we think what you'd really want to know here is the version of KVM, but that is really the host kernel version.

Do you think the host kernel version is more interesting, or the version of QEMU? From a SUSE perspective I think the QEMU version is a better fit for "VirtualizationProductInfo" than the host kernel version.

**Comment by rwmjones** [comment]
> Is Fedora doing something similar?

Not as far as I'm aware.  We do have this kind of separation, eg. systemd package config is stored in `/usr/lib/systemd` but that may be different from what you're thinking of.

> Do you think the host kernel version is more interesting, or the version of QEMU?

TBH I'm not the user of any of this, so I guess I should really be asking SAP.  Seemed unlikely that anyone would want to know the libvirt version though, QEMU or kernel would be more material for chasing bugs.

**Comment by jfehlig** [comment]
> > Is Fedora doing something similar?
> 
> Not as far as I'm aware. We do have this kind of separation, eg. systemd package config is stored in `/usr/lib/systemd` but that may be different from what you're thinking of.

I found more info regarding /etc and /usr/etc for config files

https://packageninjas.github.io/packaging/2020/10/13/news-in-packaging.html#configuration-files-in-etc-and-usretc

> TBH I'm not the user of any of this, so I guess I should really be asking SAP. 

Do you have a contact? If not, we could try Michael Trapp. I can't find him on github, but his info is in the changelog. He has contributed several patches to vhostmd over the years.

**Comment by hdeller** [comment]
On 11/30/20 10:04 PM, Jim Fehlig wrote:
> Do you have a contact? If not, we could try Michael Trapp.

You may contact the SAP LinuxLab at linux@sap.com.

Helge

**Comment by kazoconnor** [comment]
> > Is Fedora doing something similar?
> 
> Not as far as I'm aware. We do have this kind of separation, eg. systemd package config is stored in `/usr/lib/systemd` but that may be different from what you're thinking of.
> 
> > Do you think the host kernel version is more interesting, or the version of QEMU?
> 
> TBH I'm not the user of any of this, so I guess I should really be asking SAP. Seemed unlikely that anyone would want to know the libvirt version though, QEMU or kernel would be more material for chasing bugs.

SAP got back to me, basically they are looking for Hypervisor info e.g. "RHV 4.4" or "RHEL8.2 KVM" but QEMU info is fine. They have no interest in the host kernel version as it's too generic. Also they suggest using libvirt-libs instead of libvirt is fine as it should provide the same output.
rpm -q --queryformat "%{VENDOR}\n" libvirt-libs | sort -u

**Comment by shenningz** [comment]
Some more info from the SAP side: basically any query is fine for us that:
- returns Hypervisor product-related info/version
- works on SLES, RHEL and RHV,
- is able to get the info from the default or even minimum installation pattern
Qemu information was the next best thing to KVM-related info we could get.
Would libvirt-libs - or any other package - match these conditions ?

**Comment by jfehlig** [comment]
I like Rich's suggestion for VirtualizationVendor. For VirtualizationProductInfo I used 'virsh version'. Comments appreciated on the following change:
https://github.com/jfehlig/vhostmd/commit/f7808a22d0c0a77ce9d4216930c8813cd7cddefb

**Comment by jfehlig** [comment]
Cleaning up old issues. I merged the above change.
